### ISSUE TITLE
Sweep: Database Error on live application

### ISSUE THREAD

**Issue by Raza9798** [liberusoftware/real-estate-laravel#807]
### Details
![image](https://github.com/user-attachments/assets/21742e3b-db99-46fe-b4d6-476f40317f6f)

Some migrations needs to be run on your live system

**Comment by curtisdelicata** [comment]
Thank you for the report. We were busy working on new features. Started Thursday was bug fixes. Completed next few days. @Raza9798

**Comment by Raza9798** [comment]
Great just I found it randomly. Is that a open source project? @curtisdelicata

**Comment by curtisdelicata** [comment]
Yes it's open source but we offer business support and web hosting of applications at liberu.co.uk

**Comment by Raza9798** [comment]
can I contribute to the project? @curtisdelicata

**Comment by curtisdelicata** [comment]
Sure.

**Comment by Raza9798** [comment]
is there any teams? or how we can contact? there are many UI issues which are needed to be fixed. @curtisdelicata

**Comment by curtisdelicata** [comment]
Email office@liberu.co.uk and I'll send you a WhatsApp group invite... However pull requests welcome for now to assess quality of code. We do that always.

No application process for pull requests so maybe find something you want resolved and send a pull request to begin with. @Raza9798

**Comment by curtisdelicata** [comment]
Actually @Raza9798 just add this WhatsApp which is the business one +441793550342

**Comment by Raza9798** [comment]
PR https://github.com/liberu-real-estate/real-estate-laravel/pull/809 @curtisdelicata

**Comment by Raza9798** [comment]
PR requested and closing this issue
